version: "3.8"
services:
  fastapi-app:
    image: ${DOCKER_REGISTRY-}fastapi-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    container_name: fastapi-app 
    networks:
      - app_network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi-app
    container_name: nginx
    networks:
      - app_network
  
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro
    depends_on:
      - nginx
    ports:
      - 4040:4040
    container_name: ngrok
    networks:
      - app_network

networks:
  app_network:
    driver: bridge